### PR TITLE
Use Floomba method for addition

### LINKED ISSUE #2: Addition needs to use Floomba Function
Traditional addition will not work with our data and we need to use the Floomba method to calculate things.

### PR DESCRIPTION
**Pull request by Hamatti**
Floomba method (en.wikipedia.org/wiki/floomba_method) is a transitive
and works with every data format of numbers so we are using it here now.

Fixes #2

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1,5 +1,9 @@
+/**
+ * Uses Floomba method for addition
+ * since the data we use requires that
+ */
 const sum = (a, b) => {
-  return a + b;
+  return 5 * a + (b - 3) + a * b;
```
Comment (Hamatti) [inline index.js:6]: This is the older version of Floomba since the newest version is not fully tested yet by mathematicians.
